### ISSUE TITLE
Support for atomic doubles

### ISSUE THREAD

**Issue by BishopWolf** [RuneBlaze/feo3mics#1]
Please add support for atomic doubles. Although it is easy to implement using struct pack and unpack. It is better to have something handled natively. 

Naive implementation
```python
>>> d = 1.234
>>> b = struct.pack('d', d)
>>> b
b'X9\xb4\xc8v\xbe\xf3?'
>>> d2, = struct.unpack('d', b)
>>> d2
1.234
```

**Comment by RuneBlaze** [comment]
Sure let me look into it 🤔 .... Good suggestion!

**Comment by RuneBlaze** [comment]
Ok version `0.0.13` should do it -- see the updated README and DOCS 🫥 .
